Repository decentralized-hse/practice, pull requests merged in 2024-03, with the labels that each got.

#137 [01-git] Romanova Anastasia diff command
  01-git/diff-nastyaromanova-src/.gitignore
  01-git/diff-nastyaromanova-src/CMakeLists.txt
  01-git/diff-nastyaromanova-src/README.md
  01-git/diff-nastyaromanova-src/checkers.h
  01-git/diff-nastyaromanova-src/constants.h
  01-git/diff-nastyaromanova-src/diff-nastyaromanova
  01-git/diff-nastyaromanova-src/diff-nastyaromanova.cpp
  01-git/diff-nastyaromanova-src/images/example.png
  01-git/diff-nastyaromanova-src/object_info.h
Labels: help wanted, 2check

#150 [01-git][rm] Gorelyi Mikhail
  01-git/rm-gorelyi/Cargo.toml
  01-git/rm-gorelyi/src/main.rs
Labels: 2check

#149 [01-git] rm Stepan Styopkin
  01-git/rm-styopkin/Makefile
  01-git/rm-styopkin/common/dirent.c
  01-git/rm-styopkin/common/dirent.h
  01-git/rm-styopkin/common/objutil.c
  01-git/rm-styopkin/common/objutil.h
  01-git/rm-styopkin/rm.c
Labels: 2check

#154 [01-git][log] Zinchenko Danila
  01-git/log-zinchenko/README.md
  01-git/log-zinchenko/example/14bab1779c8b86c15bec26e1fe28cf2a2e6d5ef4abf0ad030a9feb323507a789
  01-git/log-zinchenko/example/377a6f550c2c0b32c38040b476b3d7f785370a98dba322e6c059bd8d4addce3e
  01-git/log-zinchenko/example/4b3bf08be4bfa1799e818ade348a9e50559afae3ae19b2b3443db350620901fc
  01-git/log-zinchenko/example/8f2b3b21335da1f9211eee0b514499d622c3b09a9bfd3dcede1e90f3633f06a6
  01-git/log-zinchenko/example/a1904686a1f37f3c7865193471b857902dbf203708f6598f8a26587e7b83ce64
  01-git/log-zinchenko/example/fcc3cc106965730cd0cc674b60dad497421d753af3a06c0195951592f22d95c7
  01-git/log-zinchenko/main.go
Labels: 2check

#162 Shubnikov java 01-git: rm
  01-git/rm-shubnikov/.gradle/8.6/checksums/checksums.lock
  01-git/rm-shubnikov/.gradle/8.6/dependencies-accessors/gc.properties
  01-git/rm-shubnikov/.gradle/8.6/executionHistory/executionHistory.bin
  01-git/rm-shubnikov/.gradle/8.6/executionHistory/executionHistory.lock
  01-git/rm-shubnikov/.gradle/8.6/fileChanges/last-build.bin
  01-git/rm-shubnikov/.gradle/8.6/fileHashes/fileHashes.bin
  01-git/rm-shubnikov/.gradle/8.6/fileHashes/fileHashes.lock
  01-git/rm-shubnikov/.gradle/8.6/fileHashes/resourceHashesCache.bin
  01-git/rm-shubnikov/.gradle/8.6/gc.properties
  01-git/rm-shubnikov/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  01-git/rm-shubnikov/.gradle/buildOutputCleanup/cache.properties
  01-git/rm-shubnikov/.gradle/buildOutputCleanup/outputFiles.bin
  01-git/rm-shubnikov/.gradle/file-system.probe
  01-git/rm-shubnikov/.gradle/vcs-1/gc.properties
  01-git/rm-shubnikov/0ba904eae8773b70c75333db4de2f3ac45a8ad4ddba1b242f0b3cfc199391dd8
  01-git/rm-shubnikov/4c474e331abf475d7432f1e68c961d4bb12c0f1f1aa167124033d92815ed3814
  01-git/rm-shubnikov/99682225f8eeb6a007bed389c124c659f596a794d556b4c865c99995c5f03b98
  01-git/rm-shubnikov/Readme.md
  01-git/rm-shubnikov/build.gradle
  01-git/rm-shubnikov/build/classes/java/main/rm/MyRm.class
  01-git/rm-shubnikov/build/distributions/rm-shubnikov.tar
  01-git/rm-shubnikov/build/distributions/rm-shubnikov.zip
  01-git/rm-shubnikov/build/libs/rm-shubnikov.jar
  01-git/rm-shubnikov/build/scripts/rm-shubnikov
  01-git/rm-shubnikov/build/scripts/rm-shubnikov.bat
  01-git/rm-shubnikov/build/tmp/compileJava/compileTransaction/stash-dir/MyRm.class.uniqueId0
  01-git/rm-shubnikov/build/tmp/compileJava/previous-compilation-data.bin
  01-git/rm-shubnikov/build/tmp/jar/MANIFEST.MF
  01-git/rm-shubnikov/dd504747dc5604cd0a7ea3386a308648847478595f959dd7a8394bdda803c428
  01-git/rm-shubnikov/e21d3a526d08ae5fac7bd69455022e2fec66b051641a1bcbbee7744e32095b02
  01-git/rm-shubnikov/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  01-git/rm-shubnikov/e4092b68424380aef3be5e6d66640cd059c31859f438d9124d5e598302faeba8
  01-git/rm-shubnikov/f21ad9b137583c2d87ca8cf3a8c14934076adf50f96f465204262315e7bfeb87
  01-git/rm-shubnikov/src/main/java/my_rm/MyRm.java
Labels: 2check

#167 [01-git][Java] Shishkina Olga
  01-git/get-shishkina/4c474e331abf475d7432f1e68c961d4bb12c0f1f1aa167124033d92815ed3814
  01-git/get-shishkina/99682225f8eeb6a007bed389c124c659f596a794d556b4c865c99995c5f03b98
  01-git/get-shishkina/GitGet.class
  01-git/get-shishkina/GitGet.java
  01-git/get-shishkina/README.md
  01-git/get-shishkina/e21d3a526d08ae5fac7bd69455022e2fec66b051641a1bcbbee7744e32095b02
Labels: 2check

#134 [01-git] log Polezhaev - Pyhton
  01-git/log-polezhaev.py
Labels: 2check

#147 [01-git] check Filippova Nadezhda
  01-git/check-filippova/README.md
  01-git/check-filippova/check.go
  01-git/check-filippova/correct_example/0ba904eae8773b70c75333db4de2f3ac45a8ad4ddba1b242f0b3cfc199391dd8
  01-git/check-filippova/correct_example/4c474e331abf475d7432f1e68c961d4bb12c0f1f1aa167124033d92815ed3814
  01-git/check-filippova/correct_example/99682225f8eeb6a007bed389c124c659f596a794d556b4c865c99995c5f03b98
  01-git/check-filippova/correct_example/dd504747dc5604cd0a7ea3386a308648847478595f959dd7a8394bdda803c428
  01-git/check-filippova/correct_example/e21d3a526d08ae5fac7bd69455022e2fec66b051641a1bcbbee7744e32095b02
  01-git/check-filippova/incorrect_example/4c474e331abf475d7432f1e68c961d4bb12c0f1f1aa167124033d92815ed3814
  01-git/check-filippova/incorrect_example/99682225f8eeb6a007bed389c124c659f596a794d556b4c865c99995c5f03b98
Labels: 2check

#159 [01-git][check] Alasheev Ivan
  01-git/check-alasheev/.clang-format
  01-git/check-alasheev/.gitignore
  01-git/check-alasheev/CMakeLists.txt
  01-git/check-alasheev/README.md
  01-git/check-alasheev/dependencies/HashLibrary.cmake
  01-git/check-alasheev/lib/CMakeLists.txt
  01-git/check-alasheev/lib/validate.cpp
  01-git/check-alasheev/lib/validate.hpp
  01-git/check-alasheev/main.cpp
Labels: 2check

#152 Ilistratov/hw2
  09-fuzz/fb-levin-listratov/.gitignore
  09-fuzz/fb-levin-listratov/fb_levin/.DS_Store
  09-fuzz/fb-levin-listratov/fb_levin/fb_levin.py
  09-fuzz/fb-levin-listratov/fb_levin/schema.fbs
  09-fuzz/fb-levin-listratov/fb_levin/schema/Project.py
  09-fuzz/fb-levin-listratov/fb_levin/schema/Root.py
  09-fuzz/fb-levin-listratov/fb_levin/schema/Student.py
  09-fuzz/fb-levin-listratov/fb_levin/schema/__init__.py
  09-fuzz/fb-levin-listratov/fuzzer.py
Labels: 2check

#166 Shubnikov-09-json-rust-fuzz: attempt 1
  09-fuzz/json_boloninid_shubnikov/.gitignore
  09-fuzz/json_boloninid_shubnikov/Cargo.lock
  09-fuzz/json_boloninid_shubnikov/Cargo.toml
  09-fuzz/json_boloninid_shubnikov/Readme.md
  09-fuzz/json_boloninid_shubnikov/fuzz/Cargo.lock
  09-fuzz/json_boloninid_shubnikov/fuzz/Cargo.toml
  09-fuzz/json_boloninid_shubnikov/fuzz/my_fuzz.rs
  09-fuzz/json_boloninid_shubnikov/src/lib.rs
  09-fuzz/json_boloninid_shubnikov/src/main.rs
  09-fuzz/json_boloninid_shubnikov/src/solve.rs
Labels: 2fix

#156 [09-fuzz] protobuf-golub-osetrov Osetrov Fedor
  09-fuzz/protobuf-golub-osetrov/.clang-format
  09-fuzz/protobuf-golub-osetrov/.gitignore
  09-fuzz/protobuf-golub-osetrov/CMakeLists.txt
  09-fuzz/protobuf-golub-osetrov/README.md
  09-fuzz/protobuf-golub-osetrov/fuzzing/CMakeLists.txt
  09-fuzz/protobuf-golub-osetrov/fuzzing/README.md
  09-fuzz/protobuf-golub-osetrov/fuzzing/fuzz.cpp
  09-fuzz/protobuf-golub-osetrov/main.cpp
  09-fuzz/protobuf-golub-osetrov/protobuf-golub-osetrov.cpp
  09-fuzz/protobuf-golub-osetrov/protobuf-golub-osetrov.hpp
  09-fuzz/protobuf-golub-osetrov/protobuf-golub-osetrov.proto
  09-fuzz/protobuf-golub-osetrov/test.sh
  09-fuzz/protobuf-golub-osetrov/third_party/Utf8Range.cmake
  09-fuzz/protobuf-golub-osetrov/utils.cpp
  09-fuzz/protobuf-golub-osetrov/utils.hpp
Labels: 2check

#157 [09-fuzz][go] artemenko
  09-fuzz/sqlite-lysenko-artemenko/fuzzer_test.go
  09-fuzz/sqlite-lysenko-artemenko/go.mod
  09-fuzz/sqlite-lysenko-artemenko/go.sum
  09-fuzz/sqlite-lysenko-artemenko/sqlite-lysenko/sqlite-lysenko.go
  09-fuzz/sqlite-lysenko-artemenko/testdata/fuzz/FuzzSqlite/07a8e0f962d8cd42
  09-fuzz/sqlite-lysenko-artemenko/testdata/fuzz/FuzzSqlite/32dc1a46637a32a9
  09-fuzz/sqlite-lysenko-artemenko/testdata/fuzz/FuzzSqlite/4279bbf387692f7b
  09-fuzz/sqlite-lysenko-artemenko/testdata/fuzz/FuzzSqlite/43e97be7a1ec0b7b
  09-fuzz/sqlite-lysenko-artemenko/testdata/fuzz/FuzzSqlite/582528ddfad69eb5
  09-fuzz/sqlite-lysenko-artemenko/testdata/fuzz/FuzzSqlite/9a104b0e1934e63b
  09-fuzz/sqlite-lysenko-artemenko/testdata/fuzz/FuzzSqlite/f429e7ed7c5134e6
Labels: 2check

#160 [09-fuzz][cpp] Kazantseva Anna
  09-fuzz/sqlite-gvasalia-kazantseva/README.md
  09-fuzz/sqlite-gvasalia-kazantseva/fuzz_me.cc
  09-fuzz/sqlite-gvasalia-kazantseva/precheck.h
  09-fuzz/sqlite-gvasalia-kazantseva/sqlite-gvasalia-kazantseva.h
Labels: 2check

#161 [09-fuzz][cpp] flatbuffers-nikulin-jilavyan
  09-fuzz/flatbuffers-nikulin-jilavyan/StudentFormat/schema.fbs
  09-fuzz/flatbuffers-nikulin-jilavyan/StudentFormat/schema_generated.h
  09-fuzz/flatbuffers-nikulin-jilavyan/bin-gritzko-check.cpp
  09-fuzz/flatbuffers-nikulin-jilavyan/bin-gritzko-check.h
  09-fuzz/flatbuffers-nikulin-jilavyan/flatbuffers-nikulin-main.cpp
  09-fuzz/flatbuffers-nikulin-jilavyan/flatbuffers-nikulin.cpp
  09-fuzz/flatbuffers-nikulin-jilavyan/flatbuffers-nikulin.h
  09-fuzz/flatbuffers-nikulin-jilavyan/fuzz.cpp
  09-fuzz/flatbuffers-nikulin-jilavyan/readme.md
Labels: 2check

#155 fuzzing-zhukova
  09-fuzz/zhukova/.gitignore
  09-fuzz/zhukova/kv-balobanov-zhukova.py
  09-fuzz/zhukova/readme.md
  09-fuzz/zhukova/requirements.txt
Labels: 2check

#163 [09-fuzz] xml-gamezardashvili shtakin - rust
  09-fuzz/xml-gamezardashvili-shtakin/Cargo.lock
  09-fuzz/xml-gamezardashvili-shtakin/Cargo.toml
  09-fuzz/xml-gamezardashvili-shtakin/README.md
  09-fuzz/xml-gamezardashvili-shtakin/fuzz/.gitignore
  09-fuzz/xml-gamezardashvili-shtakin/fuzz/Cargo.lock
  09-fuzz/xml-gamezardashvili-shtakin/fuzz/Cargo.toml
  09-fuzz/xml-gamezardashvili-shtakin/fuzz/fuzz_targets/fuzz_bin.rs
  09-fuzz/xml-gamezardashvili-shtakin/fuzz/fuzz_targets/fuzz_round_trip.rs
  09-fuzz/xml-gamezardashvili-shtakin/fuzz/fuzz_targets/fuzz_xml.rs
  09-fuzz/xml-gamezardashvili-shtakin/src/format.rs
  09-fuzz/xml-gamezardashvili-shtakin/src/lib.rs
  09-fuzz/xml-gamezardashvili-shtakin/src/main.rs
Labels: 2check

#165 [09-fuzz][Go] protobuf-akimov-shishkina
  09-fuzz/protobuf-akimov-shishkina/README.md
  09-fuzz/protobuf-akimov-shishkina/go.mod
  09-fuzz/protobuf-akimov-shishkina/go.sum
  09-fuzz/protobuf-akimov-shishkina/main.go
  09-fuzz/protobuf-akimov-shishkina/protobuf/gen/student.pb.go
  09-fuzz/protobuf-akimov-shishkina/protobuf/student.go
  09-fuzz/protobuf-akimov-shishkina/protobuf/student.proto
  09-fuzz/protobuf-akimov-shishkina/test/fuzzer_test.go
  09-fuzz/protobuf-akimov-shishkina/usecases/fromBin.go
  09-fuzz/protobuf-akimov-shishkina/usecases/fromProto.go
  09-fuzz/protobuf-akimov-shishkina/usecases/models.go
Labels: 2check

#172 [09-fuzz][cpp] Styopkin Stepan
  09-fuzz/kaurkerdevourer/sstable-aleks5d/convert.cpp
  09-fuzz/kaurkerdevourer/sstable-aleks5d/convert.h
  09-fuzz/kaurkerdevourer/sstable-aleks5d/fuzz.cc
  09-fuzz/kaurkerdevourer/sstable-aleks5d/ivanov.bin
  09-fuzz/kaurkerdevourer/sstable-aleks5d/ivanov.index
  09-fuzz/kaurkerdevourer/sstable-aleks5d/ivanov.sstable
  09-fuzz/kaurkerdevourer/sstable-aleks5d/precheck.h
  09-fuzz/kaurkerdevourer/sstable-aleks5d/readme.md
Labels: 2check

#168 09-fuzz Riabykh Albert
  09-fuzz/kv-luchsh-riabykh.go
  09-fuzz/riabykh/main_test.go
Labels: 2check

#178 [09-fuzz] fuzzing json-basalaev by ershov
  09-fuzz/json-basalaev-ershov/README.md
  09-fuzz/json-basalaev-ershov/fuzz_me.cc
  09-fuzz/json-basalaev-ershov/json-basalaev.h
  09-fuzz/json-basalaev-ershov/json.hpp
  09-fuzz/json-basalaev-ershov/precheck.h
Labels: 2check

#173 [09-fuzz][go] Bocharov Egor capnp-trenin
  09-fuzz/capnp-trenin-bocharov/README.md
  09-fuzz/capnp-trenin-bocharov/capnp-trenin/students.capnp
  09-fuzz/capnp-trenin-bocharov/capnp-trenin/students.capnp.go
  09-fuzz/capnp-trenin-bocharov/example/ivanov.bin
  09-fuzz/capnp-trenin-bocharov/fuzz_test.go
  09-fuzz/capnp-trenin-bocharov/go.mod
  09-fuzz/capnp-trenin-bocharov/go.sum
  09-fuzz/capnp-trenin-bocharov/student_validation.go
  09-fuzz/capnp-trenin-bocharov/trenin.go
Labels: 2check

#145 [01-git][log] Gaziev Saidakbar
  01-git/log-gaziev/Cargo.lock
  01-git/log-gaziev/Cargo.toml
  01-git/log-gaziev/src/main.rs
Labels: 2check

#170 [01-git][log] Bocharov
  01-git/log-bocharov/README.md
  01-git/log-bocharov/example/14bab1779c8b86c15bec26e1fe28cf2a2e6d5ef4abf0ad030a9feb323507a789
  01-git/log-bocharov/example/377a6f550c2c0b32c38040b476b3d7f785370a98dba322e6c059bd8d4addce3e
  01-git/log-bocharov/example/4b3bf08be4bfa1799e818ade348a9e50559afae3ae19b2b3443db350620901fc
  01-git/log-bocharov/example/8f2b3b21335da1f9211eee0b514499d622c3b09a9bfd3dcede1e90f3633f06a6
  01-git/log-bocharov/example/a1904686a1f37f3c7865193471b857902dbf203708f6598f8a26587e7b83ce64
  01-git/log-bocharov/example/fcc3cc106965730cd0cc674b60dad497421d753af3a06c0195951592f22d95c7
  01-git/log-bocharov/main.c
Labels: 2check

#183 [09-fuzz][Python] sqlite-savin-polezhaev
  09-fuzz/sqlite-savin-polezhaev/README.md
  09-fuzz/sqlite-savin-polezhaev/fuzz.py
  09-fuzz/sqlite-savin-polezhaev/requirements.txt
  09-fuzz/sqlite-savin-polezhaev/sqlite_savin_polezhaev.py
Labels: 2check

#184 [09-fuzz][python]json-zhukov-konstantinov
  09-fuzz/json-zhukov-konstantinov/fuzzer.py
  09-fuzz/json-zhukov-konstantinov/json_zhukov_konstantinov.py
  09-fuzz/json-zhukov-konstantinov/requirements.txt
Labels: 2check

#185 [09-fuzz][java]capnproto-usov-tolkachev
  09-fuzz/capnproto-usov-tolkachev/README.md
  09-fuzz/capnproto-usov-tolkachev/pom.xml
  09-fuzz/capnproto-usov-tolkachev/src/main/capnp/student.capnp
  09-fuzz/capnproto-usov-tolkachev/src/main/java/Formats.java
  09-fuzz/capnproto-usov-tolkachev/src/main/java/Fuzzer.java
  09-fuzz/capnproto-usov-tolkachev/src/main/java/Main.java
Labels: 2check

#186 [09-fuzzing][py] Gorelyi Mikhail
  09-fuzz/capnp-smorodinnikova-gorelyi/fuzzing.py
  09-fuzz/capnp-smorodinnikova-gorelyi/in/ivanov.bin
  09-fuzz/capnp-smorodinnikova-gorelyi/main.py
  09-fuzz/capnp-smorodinnikova-gorelyi/student.capnp
Labels: 2check

#171 [09-fuzz][C#] Kopylov Oleg kv-triapitsyn-kopylov.cs
  09-fuzz/fuzz-kopylov/.gitignore
  09-fuzz/fuzz-kopylov/Domain/Domain.csproj
  09-fuzz/fuzz-kopylov/Domain/Project.cs
  09-fuzz/fuzz-kopylov/Domain/Student.cs
  09-fuzz/fuzz-kopylov/Fuzz/Fuzz.csproj
  09-fuzz/fuzz-kopylov/Fuzz/Program.cs
  09-fuzz/fuzz-kopylov/Fuzz/Testcases/test.bin
  09-fuzz/fuzz-kopylov/Fuzz/afl-fuzz
  09-fuzz/fuzz-kopylov/Fuzz/afl-gcc
  09-fuzz/fuzz-kopylov/Fuzz/findings/.cur_input
  09-fuzz/fuzz-kopylov/Fuzz/findings/fuzzer_stats
  09-fuzz/fuzz-kopylov/Fuzz/findings/plot_data
  09-fuzz/fuzz-kopylov/Fuzz/findings/queue/id:000000,orig:test.bin
  09-fuzz/fuzz-kopylov/Fuzz/fuzzScript/fuzz.ps1
  09-fuzz/fuzz-kopylov/Fuzz/test_initial.bin
  09-fuzz/fuzz-kopylov/Fuzz/test_input.bin
  09-fuzz/fuzz-kopylov/Fuzz/test_input.kv
  09-fuzz/fuzz-kopylov/Fuzz/validFilesExamples/binFormat/test.bin
  09-fuzz/fuzz-kopylov/Fuzz/validFilesExamples/kvFormat/test.kv
  09-fuzz/fuzz-kopylov/Fuzzing.sln
  09-fuzz/fuzz-kopylov/ParseLibrary/MainParser.cs
  09-fuzz/fuzz-kopylov/ParseLibrary/MainParser.exe
  09-fuzz/fuzz-kopylov/ParseLibrary/ParseException.cs
  09-fuzz/fuzz-kopylov/ParseLibrary/ParseLibrary.csproj
  09-fuzz/fuzz-kopylov/README.md
  09-fuzz/fuzz-kopylov/telegram-cloud-photo-size-2-5440750462337930695-y.jpg
  09-fuzz/kv-triapitsyn-kopylov.cs
Labels: 2check

#174 [09-fuzz][java] Minasian Levon xml-kaledin
  09-fuzz/xml-kaledin-minasian.java
Labels: 2check

#180 [01-git][mkdir][Golang] Erdman Vladimir
  01-git/mkdir-erdman/README.md
  01-git/mkdir-erdman/mkdir.go
Labels: 2check

#153 [01-git][diff] Nardzhiev Nikita
  01-git/diff-nardzhiev/README.me
  01-git/diff-nardzhiev/__main__.py
Labels: 2check

#182 [09-fuzz][cpp] Filippova Nadezhda
  09-fuzz/xml-nasonkov-filippova/README.md
  09-fuzz/xml-nasonkov-filippova/crash.bin
  09-fuzz/xml-nasonkov-filippova/crash2.bin
  09-fuzz/xml-nasonkov-filippova/fuzz.cpp
  09-fuzz/xml-nasonkov-filippova/main.cpp
  09-fuzz/xml-nasonkov-filippova/tinyxml2.cpp
  09-fuzz/xml-nasonkov-filippova/tinyxml2.h
  09-fuzz/xml-nasonkov-filippova/xml-nasonkov
  09-fuzz/xml-nasonkov-filippova/xml-nasonkov.cpp
  09-fuzz/xml-nasonkov-filippova/xml-nasonkov.h
Labels: 2check

#190 [09-fuzz][cpp] Capnproto Kuldyusheva
  09-fuzz/capnproto-kazantsev-kuldyusheva/README.md
  09-fuzz/capnproto-kazantsev-kuldyusheva/capnproto-kazantsev-kuldyusheva.c++
  09-fuzz/capnproto-kazantsev-kuldyusheva/fuzz.cc
  09-fuzz/capnproto-kazantsev-kuldyusheva/main.cpp
  09-fuzz/capnproto-kazantsev-kuldyusheva/student.capnp.c++
  09-fuzz/capnproto-kazantsev-kuldyusheva/student.capnp.h
  09-fuzz/capnproto-kazantsev-kuldyusheva/validate.h
Labels: 2check

#196 [07-crdt][lww][cpp] Artemenko Mikhail
  07-crdt/cpp/.clang-format
  07-crdt/cpp/.gitignore
  07-crdt/cpp/CMakeLists.txt
  07-crdt/cpp/libs/CMakeLists.txt
  07-crdt/cpp/libs/cmn/CMakeLists.txt
  07-crdt/cpp/libs/cmn/id.cpp
  07-crdt/cpp/libs/cmn/id.hpp
  07-crdt/cpp/libs/ll/CMakeLists.txt
  07-crdt/cpp/libs/ll/bytes.cpp
  07-crdt/cpp/libs/ll/bytes.hpp
  07-crdt/cpp/libs/ll/zipint.cpp
  07-crdt/cpp/libs/ll/zipint.hpp
  07-crdt/cpp/libs/tlv/CMakeLists.txt
  07-crdt/cpp/libs/tlv/io.cpp
  07-crdt/cpp/libs/tlv/io.hpp
  07-crdt/cpp/libs/tlv/record.cpp
  07-crdt/cpp/libs/tlv/record.hpp
  07-crdt/cpp/lwwv-isfr-artemenko/CMakeLists.txt
  07-crdt/cpp/lwwv-isfr-artemenko/demo/CMakeLists.txt
  07-crdt/cpp/lwwv-isfr-artemenko/demo/main.cpp
  07-crdt/cpp/lwwv-isfr-artemenko/isfr/CMakeLists.txt
  07-crdt/cpp/lwwv-isfr-artemenko/isfr/types.cpp
  07-crdt/cpp/lwwv-isfr-artemenko/isfr/types.hpp
  07-crdt/cpp/tests/CMakeLists.txt
  07-crdt/cpp/tests/test_isfr.cpp
  07-crdt/cpp/tests/test_tlv.cpp
  07-crdt/cpp/tests/test_zip.cpp
  07-crdt/cpp/third_party/CMakeLists.txt
Labels: 2check

#151 [01-git][check] Hayk Manukyan
  01-git/check-manukyan/.DS_Store
  01-git/check-manukyan/Cargo.toml
  01-git/check-manukyan/README.md
  01-git/check-manukyan/fs/0ba904eae8773b70c75333db4de2f3ac45a8ad4ddba1b242f0b3cfc199391dd8
  01-git/check-manukyan/fs/4c474e331abf475d7432f1e68c961d4bb12c0f1f1aa167124033d92815ed3814
  01-git/check-manukyan/fs/99682225f8eeb6a007bed389c124c659f596a794d556b4c865c99995c5f03b98
  01-git/check-manukyan/fs/dd504747dc5604cd0a7ea3386a308648847478595f959dd7a8394bdda803c428
  01-git/check-manukyan/fs/e21d3a526d08ae5fac7bd69455022e2fec66b051641a1bcbbee7744e32095b02
  01-git/check-manukyan/fs/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  01-git/check-manukyan/fs/f21ad9b137583c2d87ca8cf3a8c14934076adf50f96f465204262315e7bfeb87
  01-git/check-manukyan/src/main.rs
  01-git/check-manukyan/src/validation.rs
Labels: 2check

#181 [01-git][rm][Python] Denis Ostashov
  01-git/rm-ostashov/README.md
  01-git/rm-ostashov/hash.py
  01-git/rm-ostashov/requirements.txt
  01-git/rm-ostashov/rm.py
  01-git/rm-ostashov/test/02553a5bca84d9e0167c8d159c1b171a126d8bbddc17198831a33a3de54648b0
  01-git/rm-ostashov/test/056c0323b4a7736575a39f010b7eae750f1841a40e24d3e0fd184ea65c15da71
  01-git/rm-ostashov/test/070a9a27734561f82925989391d27ed2b6d467ffe6308a7a60b57b8f78d81462
  01-git/rm-ostashov/test/63d54f7604d73de90dacfec2d180f2017793ed319c863ada14965cb32b4f47d3
  01-git/rm-ostashov/test/7aed1315129df81a348dfcc4a22db66a7d1924042d5a4633eb9ee952a76ee4fa
  01-git/rm-ostashov/test/c45a2ce369ad3b6b2f1463dded8215829f9ce53f210d16b2b8626b6c9d3fd845
  01-git/rm-ostashov/test/dir/input
  01-git/rm-ostashov/test/dir/input.txt
  01-git/rm-ostashov/test/e567a5ec0d998c25a39369dc97d403678d9a96e429d9d4e911b43a4f212e95e0
  01-git/rm-ostashov/test/input
  01-git/rm-ostashov/test/input.txt
Labels: 2check

#197 [01-git][python] Belyakov Sergey
  01-git/ls-belyakov.py
Labels: 2fix

#175 [01-git] Shaprunov Kirill diff Rust
  01-git/diff-shaprunov/Cargo.toml
  01-git/diff-shaprunov/src/main.rs
Labels: 2check

#193 [01-git][mkdir][C] Anton Andruschenko
  01-git/mkdir-andruschenko/.gitignore
  01-git/mkdir-andruschenko/CMakeLists.txt
  01-git/mkdir-andruschenko/README.md
  01-git/mkdir-andruschenko/mkdir.c
Labels: 2check

#187 [09-fuzz][rust] Alasheev Ivan
  09-fuzz/capnproto-smorodinov-alasheev/.gitignore
  09-fuzz/capnproto-smorodinov-alasheev/Cargo.lock
  09-fuzz/capnproto-smorodinov-alasheev/Cargo.toml
  09-fuzz/capnproto-smorodinov-alasheev/README.md
  09-fuzz/capnproto-smorodinov-alasheev/example.bin
  09-fuzz/capnproto-smorodinov-alasheev/fuzz/.gitignore
  09-fuzz/capnproto-smorodinov-alasheev/fuzz/Cargo.lock
  09-fuzz/capnproto-smorodinov-alasheev/fuzz/Cargo.toml
  09-fuzz/capnproto-smorodinov-alasheev/fuzz/fuzz_targets/fuzz_target_1.rs
  09-fuzz/capnproto-smorodinov-alasheev/schemas/students.capnp
  09-fuzz/capnproto-smorodinov-alasheev/src/build.rs
  09-fuzz/capnproto-smorodinov-alasheev/src/lib.rs
  09-fuzz/capnproto-smorodinov-alasheev/src/main.rs
  09-fuzz/capnproto-smorodinov-alasheev/src/students_capnp.rs
Labels: 2check

#188 [01-git][put][rust] Levon Minasian
  01-git/put-minasian/.gitignore
  01-git/put-minasian/Cargo.toml
  01-git/put-minasian/src/main.rs
Labels: 2check

#189 [09-fuzz][python] Nardzhiev Nikita
  09-fuzz/protobuf-vernigor-nardzhiev/README.md
  09-fuzz/protobuf-vernigor-nardzhiev/protobuf_vernigor/consts.py
  09-fuzz/protobuf-vernigor-nardzhiev/protobuf_vernigor/converters.py
  09-fuzz/protobuf-vernigor-nardzhiev/protobuf_vernigor/fuzz.py
  09-fuzz/protobuf-vernigor-nardzhiev/protobuf_vernigor/protobuf_vernigor.py
  09-fuzz/protobuf-vernigor-nardzhiev/protobuf_vernigor/student.proto
  09-fuzz/protobuf-vernigor-nardzhiev/protobuf_vernigor/utils.py
  09-fuzz/protobuf-vernigor-nardzhiev/test_data/test_input.bin
  09-fuzz/protobuf-vernigor-nardzhiev/test_data/test_input.protobuf
Labels: 2check

#200 [09-fuzz][kv][C++] Anton Andruschenko
  09-fuzz/kv-perevyshin-andruschenko/.gitignore
  09-fuzz/kv-perevyshin-andruschenko/README.md
  09-fuzz/kv-perevyshin-andruschenko/fuzzer.cpp
  09-fuzz/kv-perevyshin-andruschenko/helpers.hpp
  09-fuzz/kv-perevyshin-andruschenko/kv-perevyshin.hpp
Labels: 2check

#179 [01-git][check][C] Dmitriy Brusenin
  01-git/check-brusenin/README.md
  01-git/check-brusenin/bad_examples/0ba904eae8773b70c75333db4de2f3ac45a8ad4ddba1b242f0b3cfc199391dd8
  01-git/check-brusenin/bad_examples/47f2c9bc1a423d713c1128f3399aaff3b1a7fb24e9a625ced9c50a47f8066c9c
  01-git/check-brusenin/bad_examples/cb4da89b9bf32d238f710f4cf55242084b8b6d5557f1d32ef5fb9418d072d019
  01-git/check-brusenin/bad_examples/e2139d6601b956bdef6acc120450b5896323428160c6054f7dc32d7ea8fb1a92
  01-git/check-brusenin/bad_examples/ff1fc80d201244e50e7ac1ef4708fa796bb2bbf86f8eea06f7181c57df15aae5
  01-git/check-brusenin/build
  01-git/check-brusenin/main.c
  01-git/check-brusenin/parser.h
  01-git/check-brusenin/run
  01-git/check-brusenin/sha256.h
  01-git/check-brusenin/test
  01-git/check-brusenin/utils.h
Labels: 2check

#191 [09-fuzz][golang] Erdman Vladimir
  09-fuzz/xml-bogdanov-erdman/README.md
  09-fuzz/xml-bogdanov-erdman/main_test.go
  09-fuzz/xml-bogdanov-erdman/xml-bogdanov-erdman.go
Labels: 2check

#205 [07-crdt][map][go] Zinchenko Danila
  07-crdt/aci_test.go
  07-crdt/mel.go
  07-crdt/mkv.go
Labels: 2check

#203 [01-git][ls][C++] Oliger Nikita
  01-git/ls-oliger/README.md
  01-git/ls-oliger/example/075f093ba3d3934cee319afe10be611997da5257eae4429953419c79c4893238
  01-git/ls-oliger/example/0ae8b845f4ef9e41dee6ccae3cd9730ebc7305c874c69bde0c126f75142b7950
  01-git/ls-oliger/example/0b77aab8a605cc6fbf0e440e67ed342fa66ead51cc03f09dc331d12a74d3e0ea
  01-git/ls-oliger/example/0ba904eae8773b70c75333db4de2f3ac45a8ad4ddba1b242f0b3cfc199391dd8
  01-git/ls-oliger/example/11e8c85b6ba3532ee79e4754bd0e7dbd454c0896086a45efdac2995f258be35a
  01-git/ls-oliger/example/1f3ef7c4348a1054f51b7f1cb4ba304486ea802ac7d28def7c6d944072a5270b
  01-git/ls-oliger/example/1fc5a77d66f96d3a2c050f6b0b6652444541e377301a28be1ac07ded90fc5935
  01-git/ls-oliger/example/2e2e23daa82c23b8c4be3e4ed7f120af804bfdb4282c150778e0a0baca192603
  01-git/ls-oliger/example/329e7c01d32836f64df70b67f66ea810d9ff6893869453af30cf4f71f4eecda3
  01-git/ls-oliger/example/34206eec890a153dfee9e8632c89fcbca5536d04227cfebfa9cff130545bf348
  01-git/ls-oliger/example/358531efd7e6d0a8b3c45be79d1ffa88fb8e7d11ca6a341b6d142fd31d7937fc
  01-git/ls-oliger/example/3e400cc98aebdb4c545480983810b88aeb6b4654836a16658af603da5d242fa0
  01-git/ls-oliger/example/408a7d69ed40bfa87d1e477ae9b8147e20bfb00e29877cf32809162af6c97d63
  01-git/ls-oliger/example/41f4e7394004d3dd93001ac397b96a282dd072c58aadd0720fff9c232757a8da
  01-git/ls-oliger/example/4c474e331abf475d7432f1e68c961d4bb12c0f1f1aa167124033d92815ed3814
  01-git/ls-oliger/example/5810771daeca1bf82e484e935ad7dda0084a58acbe8be2657963187e4d202358
  01-git/ls-oliger/example/59a508d65de6cb3eb1e9ecbcbd18c8c2c49c13c736a254ab956f765637a787fd
  01-git/ls-oliger/example/59eb8958bb18d41d52720936d87136fadc464a16aee56063322d3b605a06386e
  01-git/ls-oliger/example/5da227a2d631dea83372c562523195008105117e5f4adbfe1e1544e5c57e9b73
  01-git/ls-oliger/example/5f8d16be493ccddaaaf4cfb447846748db9d9020d8b2fb173fabc1e39205a808
  01-git/ls-oliger/example/6067fbe352f74c3115d29f2f249fdb86d46572c85b77deff110b0f19e76de3a5
  01-git/ls-oliger/example/7197b4356cfac12feecb19a8af911ff326b184a5458aeb8a6d5935ba1d66e048
  01-git/ls-oliger/example/71feb562937803d2621cc2b793ad75f349fbb27b2da5b67c1269bd2e8a4a6f7f
  01-git/ls-oliger/example/77f851a6ca814a3c95883f940fe9474c0c92521669f7ba748e15cf563e1b62c5
  01-git/ls-oliger/example/7c5487668ad20d17ed05dc26f24cbd96cdd0723d214d367a2ef53553f006ce22
  01-git/ls-oliger/example/840a445c6b014ca2f74f3c1d3b97d64a6f50b801cc7cde4e057d913be8a44b30
  01-git/ls-oliger/example/8a93e3b3f78b2aac24f1c81ba4bf42a43fabc67e401ecfe7d270b02a53742291
  01-git/ls-oliger/example/8ba3fc335d54110d2b77341160f5ea72fab484cd2044358e17b7c15223a8e309
  01-git/ls-oliger/example/8ed5022dc2ef825d8f6825b642a38847011af060e9662ad5bf623186f8819fd9
  01-git/ls-oliger/example/8fbb4e6f1058451dcaf82dd5efacde1da755414714a396c9078212ae53ac811a
  01-git/ls-oliger/example/9941988d62d1b9cf16d151cfe4102910787d192237aa2ad05f22586d1d9481ef
  01-git/ls-oliger/example/99682225f8eeb6a007bed389c124c659f596a794d556b4c865c99995c5f03b98
  01-git/ls-oliger/example/9a1ecea435451f7699e7018c153a3ea4f5055d92801baa0be691fdb8bd557251
  01-git/ls-oliger/example/9a4e62253a64b3fc8d8aeab31430f5a6297e7fc024e4221610aa08423d17ece0
  01-git/ls-oliger/example/9bbb9a913d992756e5606e79ea09924790e4f480474bb477776d6faf19a9af74
  01-git/ls-oliger/example/a5156122bb1864bf32507b744ed6128d2ca26eeb6f19a85a594ae7309a3920c5
  01-git/ls-oliger/example/a52f4102bb8f1930b142ba40e517e79116fdb1f8d2ff65bdb7dbebc06196a6e3
  01-git/ls-oliger/example/a61421cfa6ca8f33b93bb7f4dede4e38ffb07f4f768c392912e5087417bc1c71
  01-git/ls-oliger/example/b84a44662e8da9db5ae2be1652385fce97029d24ae64c0161348196c6ade45bc
  01-git/ls-oliger/example/bdf6c15545b679e2500a451b7ff7c30b8784658e2a553d4913adb4651c0a78d3
  01-git/ls-oliger/example/be5f197af15ab86c5da80714344bf2e61583cdde579f778fd868fa2811819c52
  01-git/ls-oliger/example/bfe859320da8b5c490bedc02edb8a5fcba8e28f0ba2d448d50bb876973c13963
  01-git/ls-oliger/example/c04293b31190e8a0b4d60d69341393cb1e30538e3dbc17372885731c53180b9f
  01-git/ls-oliger/example/d1b2fa56b785a15b60b2aa9db0d4ff23b42c0ffd9020ff97eb39cf8cb1640c75
  01-git/ls-oliger/example/dd504747dc5604cd0a7ea3386a308648847478595f959dd7a8394bdda803c428
  01-git/ls-oliger/example/e21d3a526d08ae5fac7bd69455022e2fec66b051641a1bcbbee7744e32095b02
  01-git/ls-oliger/example/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  01-git/ls-oliger/example/eaf5f5706ee10d112939d54f3c0e164a701822e20dd4bb82bb20291d748292ca
  01-git/ls-oliger/example/f1e3321038f04dbc18ecab255b7bb7aa880a809c2c02d426f802264a86e1377c
  01-git/ls-oliger/example/f21ad9b137583c2d87ca8cf3a8c14934076adf50f96f465204262315e7bfeb87
  01-git/ls-oliger/example/f2e827d2ab627239199f639c475c7625a013fe2a8afd6696519329fda2977209
  01-git/ls-oliger/example/f7baf1bd1814f351b312e5adc0b7204bc8e455a22417190564cb4991345f945c
  01-git/ls-oliger/example/fba3b4c4e14384661b0ac2e2ec103d0e6275b483771ff4d930699cb0f0ce41f4
  01-git/ls-oliger/example/fbeffd16ac77e427ab3d9f5e6086665ba089424d0d64b39e39e3399e21ad2d0f
  01-git/ls-oliger/ls-oliger
  01-git/ls-oliger/main.cpp
Labels: 2check

#164 [05-mixnets][go] Karnaukhov Arseniy - ACK and Friends sharing
  05-mixnets/Drastijk-router-go/repl.go
  05-mixnets/Drastijk-router-go/router/node.go
  05-mixnets/Drastijk-router-go/router/peer.go
Labels: 2check

#198 [09-fuzz][c#][xml] Gaziev Saidakbar
  09-fuzz/fuzz-gaziev/FuzzBinToXml/FuzzBinToXml.csproj
  09-fuzz/fuzz-gaziev/FuzzBinToXml/Program.cs
  09-fuzz/fuzz-gaziev/FuzzBinToXml/findings/fuzz_bitmap
  09-fuzz/fuzz-gaziev/FuzzBinToXml/findings/fuzzer_stats
  09-fuzz/fuzz-gaziev/FuzzBinToXml/findings/plot_data
  09-fuzz/fuzz-gaziev/FuzzBinToXml/script/fuzz.ps1
  09-fuzz/fuzz-gaziev/FuzzBinToXml/testcases/test.bin
  09-fuzz/fuzz-gaziev/FuzzXmlToBin/FuzzXmlToBin.csproj
  09-fuzz/fuzz-gaziev/FuzzXmlToBin/Program.cs
  09-fuzz/fuzz-gaziev/FuzzXmlToBin/dictionaries/xml.dict
  09-fuzz/fuzz-gaziev/FuzzXmlToBin/findings/fuzz_bitmap
  09-fuzz/fuzz-gaziev/FuzzXmlToBin/findings/fuzzer_stats
  09-fuzz/fuzz-gaziev/FuzzXmlToBin/findings/plot_data
  09-fuzz/fuzz-gaziev/FuzzXmlToBin/script/fuzz.ps1
  09-fuzz/fuzz-gaziev/FuzzXmlToBin/testcases/test.xml
  09-fuzz/fuzz-gaziev/README.md
  09-fuzz/fuzz-gaziev/SourceProject/xml-lishudi.cs
  09-fuzz/fuzz-gaziev/XmlFmt/XmlFmt.cs
  09-fuzz/fuzz-gaziev/XmlFmt/XmlFmt.csproj
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test0.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test00.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test01.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test02.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test03.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test04.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test05.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test06.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test07.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test08.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test1.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_bin/test2.bin
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test0.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test00.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test01.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test02.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test03.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test04.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test05.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test06.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test1.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test10.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test11.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test12.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test13.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test14.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test15.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test2.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test3.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test4.xml
  09-fuzz/fuzz-gaziev/XmlFmt/test_xml/test5.xml
  09-fuzz/fuzz-gaziev/data/bin2xml.png
  09-fuzz/fuzz-gaziev/data/xml2bin.png
Labels: 2check
